apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matching-service
  name: matching-service
  namespace: g55
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: [ 'sh', '-c', 'until nc -z rabbitmq.g55.svc.cluster.local 5672; do echo waiting for rabbitmq; sleep 2; done;' ]
      containers:
        - image: docker_username/matching_service:latest
          imagePullPolicy: IfNotPresent
          name: matching-service
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Always
status: {}
