name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build and test service-question
      run: |
        cd backend/service-question
        ./mvn clean verify
        
    - name: Build and test service-user
      run: |
        cd backend/service-user
        ./mvn clean verify

  build-and-test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: |
        cd frontend
        pnpm install
        
    - name: Build frontend
      run: |
        cd frontend
        pnpm run build
        
    # - name: Run frontend tests
    #   run: |
    #     cd frontend
    #     npm test
